### ISSUE TITLE
OAuth2 Authorization Code grant support

### ISSUE THREAD

**Issue by gobo-ws** [caputomarcos/node-red-contrib-oauth2#27]
Hi,
Is it possible to use this node with OAuth2 Authorization Code grant flow?
Anyone got a demo if possible?

Thanks in advance.
/Johan

**Comment by caputomarcos** [comment]
Thks 
@gobo-ws 
![image](https://user-images.githubusercontent.com/3945941/187509413-2ae5e16f-4d1e-414a-a7a4-261391f4d7a5.png)

**Comment by gobo-ws** [comment]
Great! Thanks @caputomarcos
Unfortunately, I haven't had time to look at it yet.

**Comment by deosrc** [comment]
I think this is all related. I've been trying to get this working with Azure AD but I've run into a few issues. My app is set up in Azure AD and seems to be working. I'm getting an auth code back after some tinkering.

I've added a node and input what I believe are the correct settings:

![image](https://user-images.githubusercontent.com/50599779/205678610-7b54dd29-6ac4-4562-a72a-74f6203d8839.png)

I then click the Key icon but Azure is showing me an error page due to a missing "scope" parameter. From the MS documentation, this should be a space delimited list of the scopes. I put this into the input box but it doesn't seem to be included in the URL, even after deploying the flow.

If I add scope to the URL, the page hangs indefinitely (seems to be an Azure bug). When I inspect the network requests, it seems to be redirecting to another error page for a missing "response_type" parameter. From the Microsoft documentation, I believe this should be set to "code" (not sure if this is the same for all OAuth requests of this type). When I add this in, I am presented with the consent screen as expected and can accept.

I'm then redirected back to node red at `/oauth/redirect` and just get a blank page. I believe this is just a usability issue that there is no success message. The UI in node red doesn't update but when I make a call to `/oauth/credentials/{nodeID}` I get the expected code. Usually the page would close but I'm moving URLs between browser profiles so it loses the parent window that the JS uses. The UI in node red doesn't update but when I make a call to `/oauth/credentials/{nodeID}` I get the expected code.

When I run the flow, I'm still getting an error. It seems that the token request is missing the `redirect_uri` which has to be the same as when calling the authorize url. Again, I'm not sure if this is an Azure specific thing or should be the same for all OAuth authorization_code flows.

**Comment by deosrc** [comment]
@caputomarcos I've got a branch with the code request working and have added a success message to the redirect after login. Retrieving the code seems to be working fine (with Azure AD at least).

So far all of the changes look to be applicable to all OAuth code flow implementations: https://www.oauth.com/oauth2-servers/server-side-apps/authorization-code/

https://github.com/caputomarcos/node-red-contrib-oauth2/compare/dev...deosrc:node-red-contrib-oauth2:feature/azure-auth-code

I've not managed to get auth working with Azure yet. It seems the token endpoint is more problematic with some decisions being left up to the identity provider. For example, `client_id` and `client_secret` can be provided either in the `Authorization` header (as is in the code at the moment), or in the POST body.

**Comment by deosrc** [comment]
Managed to get it working. See #35.
